language: python
python:
  - 2.6
  - 2.7
  # 3.1 # Travis no longer supports Python 3.1
  - 3.2
  - 3.3
  - pypy
install:
  - pip install -r requirements.txt && pip install -r requirements-test.txt
  - case `python -V 2>&1` in *2.6*) pip install unittest2;; esac
script:
  - python setup.py test
